name: Publish package to GitHub Packages
on:
  push:
    branches:
      - 'Release'
      - 'Develop'

jobs:
  build:
    name: Building
    runs-on: [ubuntu-latest]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Get commit sha
        id: commit
        uses: pr-mpt/actions-commit-hash@v2
      - name: Get branch names
        id: branch-names
        uses: tj-actions/branch-names@v6

      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@yunology'
      - name: Setup package.json
        if: steps.branch-names-output.current_branch == 'Develop'
        uses: jaywcjlove/github-action-package@main
        with:
          version: ${{ steps.commit.outputs.short }}
      - run: yarn
      - run: yarn build
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
