name: Publish
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: Publish
    runs-on: [ubuntu-latest]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Setup package.json
        uses: jaywcjlove/github-action-package@main
        with:
          unset: scripts.postinstall, scripts.prepack, scripts.postpack
      - run: yarn
      - run: yarn build
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          dry-run: true

