name: Test

on:
  push:
    branches:
      - '**'
  pull_request_target:
    types:
      - opened

jobs:
  test:
    name: Testing
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [14]
        # os: [macos-latest, ubuntu-latest]
        os: [ubuntu-latest]
        typescript-version: [4.2]
    steps:
      - uses: actions/checkout@master

      - name: Install Docker
        uses: docker-practice/actions-setup-docker@master

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: Install Yarn
        run: npm install -g yarn

      - name: Set resolutions to correct typescript version
        uses: jossef/action-set-json-field@v2
        with:
          file: package.json
          field: resolutions
          value: "{ \"typescript\": \"${{ matrix.typescript-version }}\"}"
          parse_json: true

      # for yarn3
      # - name: Set Typescript version
      #  run: yarn set resolution typescript ${{ matrix.typescript-version }}

      - name: Install
        run: yarn install --ignore-scripts --netwrok-timeout 100000

      - name: Output ts version
        run: yarn tsc --version

      - name: Output packages version
        run: yarn list

      - name: Build
        run: yarn run build

      - name: Lint
        run: echo "Ignore lint temporary, since we have a lot lint error to deal with."
      #  run: yarn run lint

      - name: Build Docker Stack
        run: echo "Test script will auto up and down."

      - name: Test
        run: yarn run test coverage
